# Generated by Django 5.0.4 on 2024-04-18 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effect', models.TextField(unique=True, verbose_name='Effect')),
                ('benefit', models.BooleanField(verbose_name='Benefit')),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Inci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inci_name', models.TextField(unique=True, verbose_name='INCI')),
                ('description', models.TextField(null=True, unique=True, verbose_name='Description')),
                ('source', models.TextField(null=True, verbose_name='Source')),
                ('vegan', models.BooleanField(null=True, verbose_name='Vegan')),
            ],
            options={
                'db_table': 'inci',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recom', models.TextField(unique=True, verbose_name='Recommendation')),
            ],
            options={
                'db_table': 'recom',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(unique=True, verbose_name='Type')),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comb_type', models.CharField(choices=[('Yes', 'Yes'), ('Carefully', 'Carefully'), ('No', 'No')], max_length=10)),
                ('combination', models.TextField(unique=True, verbose_name='Combination')),
                ('inci_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inci_1', to='application.inci', verbose_name='Inci 1')),
                ('inci_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inci_2', to='application.inci', verbose_name='Inci 2')),
            ],
            options={
                'db_table': 'combination',
            },
        ),
        migrations.CreateModel(
            name='InciFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.feature', verbose_name='Feature')),
                ('inci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.inci', verbose_name='Inci')),
            ],
            options={
                'db_table': 'inci_feature',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.TextField(unique=True, verbose_name='Ingredient')),
                ('inci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.inci', verbose_name='INCI')),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='InciRecom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.inci', verbose_name='Inci')),
                ('recom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.recommendation', verbose_name='Recommendation')),
            ],
            options={
                'db_table': 'inci_recom',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingr_list', models.TextField(unique=True, verbose_name='List')),
                ('brand_name', models.TextField(null=True, verbose_name='Brand')),
                ('product_name', models.TextField(null=True, verbose_name='Product')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User id')),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.AddField(
            model_name='inci',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.type', verbose_name='Type'),
        ),
    ]
