# Generated by Django 5.0.4 on 2024-04-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_description',
            field=models.TextField(null=True, verbose_name='Type description'),
        ),
    ]
