# Generated by Django 5.0.4 on 2024-04-19 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_type_type_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inci',
            name='type_id',
        ),
        migrations.CreateModel(
            name='InciType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conc', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default=('High', 'High'), null=True, verbose_name='Concentration')),
                ('inci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.inci', verbose_name='Inci')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.type', verbose_name='Type')),
            ],
            options={
                'db_table': 'inci_type',
            },
        ),
    ]
