# Generated by Django 5.0.4 on 2024-04-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_inci_type_id_incitype'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_short',
            field=models.TextField(default='TYPE', unique=True, verbose_name='Type short'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='type_description',
            field=models.TextField(default='type', unique=True, verbose_name='Type description'),
            preserve_default=False,
        ),
    ]
