# Generated by Django 5.0.4 on 2024-05-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_skin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skin',
            new_name='SkinTypes',
        ),
        migrations.AlterModelTable(
            name='skintypes',
            table='skin_types',
        ),
    ]
